import type { Profile } from "@/lib/types/database";
import type { FormFieldRole } from "./types";

export type IdentityFieldRole = "full_name" | "first_name" | "last_name" | "email" | "phone";
export type DocumentFieldRole = "resume" | "cover_letter";

const IDENTITY_ROLES: readonly IdentityFieldRole[] = ["full_name", "first_name", "last_name", "email", "phone"];
const DOCUMENT_ROLES: readonly DocumentFieldRole[] = ["resume", "cover_letter"];

export function isIdentityRole(role: FormFieldRole | undefined): role is IdentityFieldRole {
  return role !== undefined && (IDENTITY_ROLES as readonly string[]).includes(role);
}

export function isDocumentRole(role: FormFieldRole | undefined): role is DocumentFieldRole {
  return role !== undefined && (DOCUMENT_ROLES as readonly string[]).includes(role);
}

/**
 * Resolves a structured identity value directly from the profile — never
 * via answerQuestion()/the Answer Library, and first_name/last_name are
 * NEVER split or inferred from full_name (profile.first_name/last_name
 * exist specifically so a real submission never has to guess a split;
 * see migration 0007). Returns null when the structured field itself is
 * empty/unset, which callers must treat as "no safe answer" — manual_required
 * if the field is required, silently omitted if optional — never fabricated.
 */
export function resolveIdentityFieldValue(role: IdentityFieldRole, profile: Profile): string | null {
  switch (role) {
    case "full_name":
      return profile.full_name?.trim() || null;
    case "first_name":
      return profile.first_name?.trim() || null;
    case "last_name":
      return profile.last_name?.trim() || null;
    case "email":
      return profile.email?.trim() || null;
    case "phone":
      return profile.phone?.trim() || null;
  }
}

/**
 * Whether the already-prepared document data for this role exists. Both
 * documents are already generated by the time a form is inspected
 * (resume tailoring and cover letter generation always run first, with a
 * safe non-AI fallback when no CV parse/OpenAI key is available), so this
 * is mostly a defensive check rather than a live risk — but a field
 * requiring a document this run genuinely has none for must still stop
 * the application rather than submit an empty one.
 */
export function hasDocumentData(role: DocumentFieldRole, documents: { resumeText: string; coverLetterText: string }): boolean {
  if (role === "resume") return documents.resumeText.trim().length > 0;
  return documents.coverLetterText.trim().length > 0;
}
