import type {
  ApplicationMethod,
  EmploymentType,
  ExperienceLevel,
  WorkType,
} from "@/lib/types/database";

export interface DemoJob {
  id: string;
  title: string;
  companyName: string;
  companyLogo?: string;
  industry: string;
  description: string;
  responsibilities: string;
  requirements: string;
  skills: string[];
  salaryMin: number;
  salaryMax: number;
  salaryCurrency: string;
  locality: string;
  remoteType: WorkType;
  employmentType: EmploymentType;
  experienceLevel: ExperienceLevel;
  postedDaysAgo: number;
  expiresInDays: number;
  applicationMethod: ApplicationMethod;
  applicationProvider?: string;
  autoApplySupported: boolean;
}

/**
 * Realistic sample Malta postings used when no live job source is
 * configured (spec §48). Clearly a fabricated dataset for demo purposes —
 * ingested through DemoJobSourceAdapter with source = "demo" so nothing
 * here is ever confused with a real employer application.
 */
export const DEMO_JOBS: DemoJob[] = [
  {
    id: "demo-001",
    title: "Senior Software Engineer",
    companyName: "Azzura Digital",
    industry: "iGaming",
    description:
      "Join our platform team building the real-money gaming backend used across Southern Europe. You'll work on high-throughput services handling millions of transactions a day.",
    responsibilities:
      "Design and own backend services · Mentor junior engineers · Participate in on-call rotation · Collaborate with product on roadmap.",
    requirements:
      "4+ years professional experience with React, TypeScript and Node.js · Comfortable with AWS · Experience with distributed systems is a plus.",
    skills: ["React", "TypeScript", "Node.js", "AWS", "PostgreSQL"],
    salaryMin: 45000,
    salaryMax: 60000,
    salaryCurrency: "EUR",
    locality: "Sliema",
    remoteType: "hybrid",
    employmentType: "full_time",
    experienceLevel: "senior",
    postedDaysAgo: 1,
    expiresInDays: 29,
    applicationMethod: "ats",
    applicationProvider: "greenhouse",
    autoApplySupported: true,
  },
  {
    id: "demo-002",
    title: "Marketing Executive",
    companyName: "Blue Lagoon Hospitality Group",
    industry: "Tourism & Hospitality",
    description:
      "Drive digital campaigns for a portfolio of boutique hotels across Malta and Gozo, from paid social to influencer partnerships.",
    responsibilities: "Plan seasonal campaigns · Manage social channels · Report on ROI · Coordinate with agencies.",
    requirements: "2+ years in digital marketing · Strong copywriting · Experience with Meta Ads and Google Analytics.",
    skills: ["Digital Marketing", "SEO", "Content Strategy", "Google Analytics"],
    salaryMin: 24000,
    salaryMax: 30000,
    salaryCurrency: "EUR",
    locality: "St Julian's",
    remoteType: "onsite",
    employmentType: "full_time",
    experienceLevel: "mid",
    postedDaysAgo: 3,
    expiresInDays: 27,
    applicationMethod: "email",
    autoApplySupported: true,
  },
  {
    id: "demo-003",
    title: "Junior Financial Analyst",
    companyName: "Meridian Fund Services",
    industry: "Financial Services",
    description: "Support the fund accounting team preparing NAV calculations and investor reporting for a growing book of alternative funds.",
    responsibilities: "Prepare NAV packs · Reconcile positions · Assist audits · Liaise with custodians.",
    requirements: "Degree in Accountancy/Finance or ACCA part-qualified · Strong Excel · Attention to detail.",
    skills: ["Excel", "Fund Accounting", "Financial Reporting"],
    salaryMin: 22000,
    salaryMax: 27000,
    salaryCurrency: "EUR",
    locality: "Ta' Xbiex",
    remoteType: "hybrid",
    employmentType: "full_time",
    experienceLevel: "junior",
    postedDaysAgo: 5,
    expiresInDays: 25,
    applicationMethod: "manual",
    autoApplySupported: false,
  },
  {
    id: "demo-004",
    title: "Product Designer (UX/UI)",
    companyName: "Northbay Software",
    industry: "Technology",
    description: "Shape the end-to-end experience of a B2B SaaS product used by logistics companies across the Mediterranean.",
    responsibilities: "Own design system · Run user research · Prototype in Figma · Partner closely with engineering.",
    requirements: "3+ years product design experience · Strong portfolio · Figma expert.",
    skills: ["Figma", "UX Research", "Design Systems", "Prototyping"],
    salaryMin: 32000,
    salaryMax: 42000,
    salaryCurrency: "EUR",
    locality: "Gżira",
    remoteType: "remote",
    employmentType: "full_time",
    experienceLevel: "mid",
    postedDaysAgo: 2,
    expiresInDays: 28,
    applicationMethod: "ats",
    applicationProvider: "lever",
    autoApplySupported: true,
  },
  {
    id: "demo-005",
    title: "Warehouse Operative",
    companyName: "Portomaso Logistics",
    industry: "Logistics",
    description: "Support daily warehouse operations at our Luqa distribution centre, including receiving, picking and dispatch.",
    responsibilities: "Pick and pack orders · Operate forklift (training provided) · Maintain stock accuracy.",
    requirements: "Physically fit · Reliable · Driving licence an advantage.",
    skills: ["Warehouse Operations", "Inventory Management"],
    salaryMin: 18000,
    salaryMax: 21000,
    salaryCurrency: "EUR",
    locality: "Luqa",
    remoteType: "onsite",
    employmentType: "full_time",
    experienceLevel: "entry",
    postedDaysAgo: 6,
    expiresInDays: 24,
    applicationMethod: "manual",
    autoApplySupported: false,
  },
  {
    id: "demo-006",
    title: "Customer Support Specialist (German Speaking)",
    companyName: "Azzura Digital",
    industry: "iGaming",
    description: "Provide first-class support to German-speaking players via chat and email, working rotating shifts.",
    responsibilities: "Handle player queries · Escalate technical issues · Maintain CSAT targets.",
    requirements: "Fluent German and English · Previous customer support experience preferred.",
    skills: ["Customer Support", "German", "Zendesk"],
    salaryMin: 21000,
    salaryMax: 25000,
    salaryCurrency: "EUR",
    locality: "St Julian's",
    remoteType: "hybrid",
    employmentType: "full_time",
    experienceLevel: "entry",
    postedDaysAgo: 1,
    expiresInDays: 29,
    applicationMethod: "ats",
    applicationProvider: "greenhouse",
    autoApplySupported: true,
  },
  {
    id: "demo-007",
    title: "DevOps Engineer",
    companyName: "Northbay Software",
    industry: "Technology",
    description: "Own our CI/CD pipelines and cloud infrastructure as we scale to new markets.",
    responsibilities: "Manage Kubernetes clusters · Improve deployment pipelines · Own observability stack.",
    requirements: "3+ years DevOps/SRE experience · Kubernetes, Terraform, AWS.",
    skills: ["Kubernetes", "Terraform", "AWS", "CI/CD"],
    salaryMin: 40000,
    salaryMax: 55000,
    salaryCurrency: "EUR",
    locality: "Gżira",
    remoteType: "remote",
    employmentType: "full_time",
    experienceLevel: "senior",
    postedDaysAgo: 4,
    expiresInDays: 26,
    applicationMethod: "ats",
    applicationProvider: "lever",
    autoApplySupported: true,
  },
  {
    id: "demo-008",
    title: "HR Generalist",
    companyName: "Meridian Fund Services",
    industry: "Financial Services",
    description: "Support the full employee lifecycle for a 120-person financial services firm.",
    responsibilities: "Onboarding & offboarding · Payroll liaison · Employee relations · Policy updates.",
    requirements: "2+ years HR experience · Knowledge of Maltese employment law a plus.",
    skills: ["HR", "Employee Relations", "Payroll"],
    salaryMin: 26000,
    salaryMax: 32000,
    salaryCurrency: "EUR",
    locality: "Ta' Xbiex",
    remoteType: "onsite",
    employmentType: "full_time",
    experienceLevel: "mid",
    postedDaysAgo: 8,
    expiresInDays: 22,
    applicationMethod: "manual",
    autoApplySupported: false,
  },
  {
    id: "demo-009",
    title: "Sous Chef",
    companyName: "Blue Lagoon Hospitality Group",
    industry: "Tourism & Hospitality",
    description: "Lead a section of our kitchen brigade at a 5-star seafront resort, delivering Mediterranean fine dining.",
    responsibilities: "Manage section during service · Train commis chefs · Maintain HACCP standards.",
    requirements: "3+ years kitchen experience · Food safety certification.",
    skills: ["Culinary Arts", "Kitchen Management", "HACCP"],
    salaryMin: 27000,
    salaryMax: 33000,
    salaryCurrency: "EUR",
    locality: "Mellieħa",
    remoteType: "onsite",
    employmentType: "full_time",
    experienceLevel: "mid",
    postedDaysAgo: 2,
    expiresInDays: 28,
    applicationMethod: "email",
    autoApplySupported: true,
  },
  {
    id: "demo-010",
    title: "Data Analyst Intern",
    companyName: "Northbay Software",
    industry: "Technology",
    description: "6-month paid internship supporting the analytics team with dashboards and ad-hoc reporting.",
    responsibilities: "Build SQL queries · Maintain dashboards · Support experiments analysis.",
    requirements: "Studying towards a degree in a quantitative field · SQL basics · Curious mindset.",
    skills: ["SQL", "Excel", "Data Visualization"],
    salaryMin: 12000,
    salaryMax: 14000,
    salaryCurrency: "EUR",
    locality: "Gżira",
    remoteType: "hybrid",
    employmentType: "internship",
    experienceLevel: "internship",
    postedDaysAgo: 10,
    expiresInDays: 20,
    applicationMethod: "ats",
    applicationProvider: "lever",
    autoApplySupported: true,
  },
  {
    id: "demo-011",
    title: "Registered Nurse",
    companyName: "St Andrew's Medical Group",
    industry: "Healthcare",
    description: "Provide high-quality patient care across our private inpatient wards.",
    responsibilities: "Patient assessment and care · Medication administration · Liaise with consultants.",
    requirements: "Valid nursing licence recognised in Malta · Minimum 1 year post-qualification experience.",
    skills: ["Patient Care", "Clinical Documentation"],
    salaryMin: 25000,
    salaryMax: 31000,
    salaryCurrency: "EUR",
    locality: "Balzan",
    remoteType: "onsite",
    employmentType: "full_time",
    experienceLevel: "junior",
    postedDaysAgo: 7,
    expiresInDays: 23,
    applicationMethod: "manual",
    autoApplySupported: false,
  },
  {
    id: "demo-012",
    title: "Backend Engineer (Python)",
    companyName: "Meridian Fund Services",
    industry: "Financial Services",
    description: "Build internal tooling automating fund reporting workflows using Python and modern data pipelines.",
    responsibilities: "Develop internal APIs · Automate reporting · Own data pipeline reliability.",
    requirements: "3+ years Python · SQL · Interest in fintech.",
    skills: ["Python", "SQL", "APIs", "Docker"],
    salaryMin: 38000,
    salaryMax: 48000,
    salaryCurrency: "EUR",
    locality: "Ta' Xbiex",
    remoteType: "hybrid",
    employmentType: "full_time",
    experienceLevel: "mid",
    postedDaysAgo: 3,
    expiresInDays: 27,
    applicationMethod: "ats",
    applicationProvider: "greenhouse",
    autoApplySupported: true,
  },
  {
    id: "demo-013",
    title: "Retail Sales Associate",
    companyName: "Valletta Waterfront Boutiques",
    industry: "Retail",
    description: "Deliver exceptional customer experiences in our flagship boutique on the Valletta Waterfront.",
    responsibilities: "Greet and assist customers · Process sales · Merchandise displays.",
    requirements: "Customer-facing experience · Friendly and proactive attitude.",
    skills: ["Retail", "Customer Service"],
    salaryMin: 18500,
    salaryMax: 20500,
    salaryCurrency: "EUR",
    locality: "Valletta",
    remoteType: "onsite",
    employmentType: "part_time",
    experienceLevel: "entry",
    postedDaysAgo: 1,
    expiresInDays: 29,
    applicationMethod: "manual",
    autoApplySupported: false,
  },
  {
    id: "demo-014",
    title: "QA Automation Engineer",
    companyName: "Azzura Digital",
    industry: "iGaming",
    description: "Own our end-to-end automation suite across web and mobile clients for our real-money gaming platform.",
    responsibilities: "Build Playwright test suites · Integrate tests into CI · Triage regressions with engineering.",
    requirements: "2+ years QA automation · Playwright or similar · CI/CD familiarity.",
    skills: ["Playwright", "TypeScript", "CI/CD", "QA"],
    salaryMin: 30000,
    salaryMax: 40000,
    salaryCurrency: "EUR",
    locality: "Sliema",
    remoteType: "hybrid",
    employmentType: "full_time",
    experienceLevel: "mid",
    postedDaysAgo: 5,
    expiresInDays: 25,
    applicationMethod: "ats",
    applicationProvider: "greenhouse",
    autoApplySupported: true,
  },
  {
    id: "demo-015",
    title: "Executive Assistant to CEO",
    companyName: "Meridian Fund Services",
    industry: "Financial Services",
    description: "Provide high-level administrative support to the CEO of a fast-growing fund administrator.",
    responsibilities: "Manage calendar and travel · Prepare board materials · Coordinate stakeholder communications.",
    requirements: "5+ years EA experience supporting senior executives · Discretion and polish.",
    skills: ["Executive Support", "Calendar Management", "Communication"],
    salaryMin: 30000,
    salaryMax: 38000,
    salaryCurrency: "EUR",
    locality: "Ta' Xbiex",
    remoteType: "onsite",
    employmentType: "full_time",
    experienceLevel: "senior",
    postedDaysAgo: 9,
    expiresInDays: 21,
    applicationMethod: "manual",
    autoApplySupported: false,
  },
  {
    id: "demo-016",
    title: "Mobile Engineer (React Native)",
    companyName: "Northbay Software",
    industry: "Technology",
    description: "Build and ship features for our cross-platform logistics tracking app used by drivers across the Mediterranean.",
    responsibilities: "Ship React Native features · Optimise app performance · Collaborate with backend team.",
    requirements: "3+ years mobile development · React Native · Familiarity with native modules.",
    skills: ["React Native", "TypeScript", "Mobile"],
    salaryMin: 36000,
    salaryMax: 46000,
    salaryCurrency: "EUR",
    locality: "Gżira",
    remoteType: "remote",
    employmentType: "full_time",
    experienceLevel: "mid",
    postedDaysAgo: 2,
    expiresInDays: 28,
    applicationMethod: "ats",
    applicationProvider: "lever",
    autoApplySupported: true,
  },
  {
    id: "demo-017",
    title: "Compliance Officer",
    companyName: "Meridian Fund Services",
    industry: "Financial Services",
    description: "Ensure regulatory compliance across our fund administration operations, liaising with the MFSA.",
    responsibilities: "Monitor regulatory changes · Conduct internal audits · Prepare MFSA submissions.",
    requirements: "3+ years compliance experience in financial services · Knowledge of MFSA regulations.",
    skills: ["Regulatory Compliance", "AML", "Risk Management"],
    salaryMin: 34000,
    salaryMax: 44000,
    salaryCurrency: "EUR",
    locality: "Ta' Xbiex",
    remoteType: "hybrid",
    employmentType: "full_time",
    experienceLevel: "senior",
    postedDaysAgo: 6,
    expiresInDays: 24,
    applicationMethod: "manual",
    autoApplySupported: false,
  },
  {
    id: "demo-018",
    title: "Bartender",
    companyName: "Blue Lagoon Hospitality Group",
    industry: "Tourism & Hospitality",
    description: "Craft cocktails and deliver memorable guest experiences at our rooftop bar overlooking St Paul's Bay.",
    responsibilities: "Prepare drinks to standard · Upsell premium offerings · Maintain bar cleanliness.",
    requirements: "Previous bartending experience · Passion for hospitality.",
    skills: ["Mixology", "Customer Service"],
    salaryMin: 19000,
    salaryMax: 23000,
    salaryCurrency: "EUR",
    locality: "St Paul's Bay",
    remoteType: "onsite",
    employmentType: "full_time",
    experienceLevel: "entry",
    postedDaysAgo: 4,
    expiresInDays: 26,
    applicationMethod: "email",
    autoApplySupported: true,
  },
  {
    id: "demo-019",
    title: "Engineering Manager",
    companyName: "Azzura Digital",
    industry: "iGaming",
    description: "Lead a team of 8 engineers building core platform services for our real-money gaming products.",
    responsibilities: "Coach and grow engineers · Own delivery roadmap · Partner with product leadership.",
    requirements: "2+ years engineering management · Strong technical background in backend systems.",
    skills: ["Engineering Management", "Node.js", "System Design"],
    salaryMin: 60000,
    salaryMax: 78000,
    salaryCurrency: "EUR",
    locality: "Sliema",
    remoteType: "hybrid",
    employmentType: "full_time",
    experienceLevel: "lead",
    postedDaysAgo: 1,
    expiresInDays: 29,
    applicationMethod: "ats",
    applicationProvider: "greenhouse",
    autoApplySupported: true,
  },
  {
    id: "demo-020",
    title: "Primary School Teacher",
    companyName: "St Andrew's Medical Group Foundation School",
    industry: "Education",
    description: "Teach a Year 4 class in a warm, bilingual (English/Maltese) learning environment.",
    responsibilities: "Plan and deliver lessons · Assess student progress · Communicate with parents.",
    requirements: "Teaching qualification recognised in Malta · Warden's Certificate.",
    skills: ["Primary Education", "Classroom Management"],
    salaryMin: 21000,
    salaryMax: 26000,
    salaryCurrency: "EUR",
    locality: "Attard",
    remoteType: "onsite",
    employmentType: "full_time",
    experienceLevel: "junior",
    postedDaysAgo: 12,
    expiresInDays: 18,
    applicationMethod: "manual",
    autoApplySupported: false,
  },
  {
    id: "demo-021",
    title: "Content Marketing Manager",
    companyName: "Northbay Software",
    industry: "Technology",
    description: "Own our content strategy across blog, case studies and social channels to support demand generation.",
    responsibilities: "Plan editorial calendar · Write and edit long-form content · Partner with sales on collateral.",
    requirements: "4+ years B2B content marketing · Excellent written English · SEO knowledge.",
    skills: ["Content Marketing", "SEO", "B2B Marketing"],
    salaryMin: 32000,
    salaryMax: 40000,
    salaryCurrency: "EUR",
    locality: "Gżira",
    remoteType: "remote",
    employmentType: "full_time",
    experienceLevel: "mid",
    postedDaysAgo: 3,
    expiresInDays: 27,
    applicationMethod: "ats",
    applicationProvider: "lever",
    autoApplySupported: true,
  },
  {
    id: "demo-022",
    title: "Electrician",
    companyName: "Portomaso Logistics",
    industry: "Facilities & Engineering",
    description: "Maintain and repair electrical systems across our Luqa and Birżebbuġa facilities.",
    responsibilities: "Diagnose electrical faults · Perform preventive maintenance · Ensure safety compliance.",
    requirements: "Licensed electrician · 2+ years commercial/industrial experience.",
    skills: ["Electrical Maintenance", "Safety Compliance"],
    salaryMin: 24000,
    salaryMax: 29000,
    salaryCurrency: "EUR",
    locality: "Birżebbuġa",
    remoteType: "onsite",
    employmentType: "full_time",
    experienceLevel: "mid",
    postedDaysAgo: 5,
    expiresInDays: 25,
    applicationMethod: "manual",
    autoApplySupported: false,
  },
  {
    id: "demo-023",
    title: "Junior Frontend Developer",
    companyName: "Azzura Digital",
    industry: "iGaming",
    description: "Kickstart your frontend career building responsive player-facing interfaces used by thousands daily.",
    responsibilities: "Build UI components · Fix bugs · Pair with senior engineers · Write tests.",
    requirements: "0-2 years experience · Solid HTML/CSS/JavaScript fundamentals · Eagerness to learn React.",
    skills: ["JavaScript", "HTML", "CSS", "React"],
    salaryMin: 22000,
    salaryMax: 27000,
    salaryCurrency: "EUR",
    locality: "Sliema",
    remoteType: "hybrid",
    employmentType: "full_time",
    experienceLevel: "entry",
    postedDaysAgo: 2,
    expiresInDays: 28,
    applicationMethod: "ats",
    applicationProvider: "greenhouse",
    autoApplySupported: true,
  },
  {
    id: "demo-024",
    title: "Operations Manager, Gozo",
    companyName: "Blue Lagoon Hospitality Group",
    industry: "Tourism & Hospitality",
    description: "Oversee day-to-day operations for our Gozo property portfolio, from housekeeping to guest relations.",
    responsibilities: "Manage department heads · Own guest satisfaction scores · Control operating budget.",
    requirements: "5+ years hospitality operations experience · Proven leadership track record.",
    skills: ["Operations Management", "Hospitality", "Leadership"],
    salaryMin: 38000,
    salaryMax: 48000,
    salaryCurrency: "EUR",
    locality: "Xagħra",
    remoteType: "onsite",
    employmentType: "full_time",
    experienceLevel: "lead",
    postedDaysAgo: 8,
    expiresInDays: 22,
    applicationMethod: "email",
    autoApplySupported: true,
  },
];
